Лабораторная работа 1
Kefi228/BaseObjectTypePython pull request #1
Opened 2023-10-13 12:57 UTC by Kefi228

Интересные задачки 👍

2023-10-14 18:08 UTC, aeksei requested changes
3.5 из 4 баллов. 
Очень хорошая работа, продолжайте в том же духе! 

---
Комментарии делятся на следующие категории:
- `GOOD` - хорошее решение. Хорошее или креативное решение.
- `TODO` - можно лучше. Эти замечания не влияют на оценку, и носят рекомендательный характер.
- `FIXME` - необходимо исправить. Устраните эти замечания, чтобы получить максимальный балл. 

---
После проверки работа, может содержать несколько статусов:
- **Changes requested**. Следует выполнить доработки, чтобы получить максимальный балл.  
	Исправление замечаний следует проводить в IDE и приложить согласно инструкции в этот pull request исправленные файлы. Файлы с исправлениями прикладывайте с теми же названиями!
- **Changes approved**. Работа выполнена на максимальный балл.  
	Рекомендуется учесть комментарии рекомендательного характера, и приложить в этот pull request исправленные файлы. В этом случае повторно на проверку присылать работу не нужно. Можно нажимать зеленую кнопку `Merge pull request`.

2023-10-14 18:08 UTC, aeksei commented on Лабораторная работа 1/task_1.py
> +numbers[4] = sum(numbers[:4] + numbers[5:]) / len(numbers)
# TODO

Индекс 4 выглядит как "магическое число". Рекомендую завести дополнительную переменную, например, `missing_index = 4` и использовать её по коду. Заведя такую переменную и заполнив её пока что вручную, можно в будущем доработать так, чтобы эта переменная вычислялась автоматизированно.

2023-10-14 18:08 UTC, aeksei commented on Лабораторная работа 1/task_1.py
1 балл

2023-10-14 18:08 UTC, aeksei commented on Лабораторная работа 1/task_2.py
1 балл

2023-10-14 18:08 UTC, aeksei commented on Лабораторная работа 1/task_3.py
> +print(list_players[int(count_players / 2):])
# FIXME

Вместо того, чтобы делить на 2 и приводить к целому числу воспользуйтесь целочисленным делением на 2.

2023-10-14 18:08 UTC, aeksei commented on Лабораторная работа 1/task_3.py
0.5 балла

2023-10-14 18:08 UTC, aeksei commented on Лабораторная работа 1/task_4.py
1 балл

2023-10-14 18:40 UTC, aeksei commented
И дополнительно приложите, пожалуйста, скрин с пройденными проверками заданий лабораторной работы в IDE

2023-10-14 21:33 UTC, Kefi228 commented on Лабораторная работа 1/task_3.py
![image](https://github.com/Kefi228/BaseObjectTypePython/assets/129835949/b0790e01-dda6-4b61-ad46-d4546f9cfc83)

2023-10-14 21:47 UTC, Kefi228 reviewed
![image](https://github.com/Kefi228/BaseObjectTypePython/assets/129835949/523da2ae-debe-432a-8512-37d6c6184e58)

2023-10-14 21:50 UTC, Kefi228 reviewed
Добавлены исправления

2023-10-15 14:37 UTC, aeksei approved these changes
Максимальный балл

2023-10-15 14:37 UTC, aeksei commented on Лабораторная работа 1/task_1.py
> +numbers[missing_index] = sum(numbers[:4] + numbers[5:]) / len(numbers)
# TODO

Только надо переменную `missing_index` использовать)) `sum(numbers[:missing_index] + numbers[missing_index+1:])`

2023-10-15 14:37 UTC, aeksei commented on Лабораторная работа 1/task_3.py
> +print(list_players[count_players // 2:])
# TODO

`count_players // 2` запишите в отдельную переменную. Получится убить сразу двух зайцев: избавиться от магических чисел и соблюсти принцип [DRY](https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself)

2023-10-15 15:04 UTC, merged